version: '3.8'

services:
  backend:
    build:
      context: ./secure-backend
      dockerfile: Dockerfile
    image: secureshop-backend:latest
    container_name: secureshop-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - GIN_MODE=release
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - TZ=UTC
    networks:
      - secureshop-network
    # Healthcheck is defined in Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./secure-frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    image: secureshop-frontend:latest
    container_name: secureshop-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - secureshop-network
    # Healthcheck is defined in Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  secureshop-network:
    driver: bridge
